elevenlabs/elevenlabs-docs

api-reference/text-to-speech-websockets.mdx
mint.json

Adds input streaming docs, protocol overview, message types and some e2e examples.

Add input streaming documentation

---

mint.json

Adding Google Analytics tracking so that we can properly track /docs users.

Add Google Analytics

---

api-reference/websockets.mdx

- Fixed a minor typo in line 381

fix: DOCS - Fixed a typo in the Websocket page

---

api-reference/how-to-use-pronunciation-dictionary-in-python.mdx

@lharries please review the draft from me. Thanks!

Added pronunciation dictionary tutorial

---

api-reference/how-to-use-request-stitching.mdx

Changes:
- Always uppercase Request Stitching

uppercase Request Stitching

---

api-reference/how-to-use-request-stitching.mdx

Changes:
- Fix tex conditioning example for Request Stitching

Fix text conditioning example

---

api-reference/streaming-with-timestamps.mdx
api-reference/text-to-speech-with-timestamps.mdx
mint.json

Changes:
- Add endpoints for new TTS with timestamps and streaming TTS with timestamps endpoints

Add endpoints for new TTS with timestamps and streaming TTS with timestamps endpoints

---

mint.json

adds posthog analytics to the docs
Note: this disables the mintlify analytics

add posthog analytics to docs

---

api-reference/sound-generation.mdx
mint.json

Changes:
- Adds a sound effect API reference page

Add sound effects API reference documentation page

---

api-reference/create-dub.mdx

Follow up to https://github.com/elevenlabs/xi/pull/3089

[Dubbing] Remove info for internal endpoint

---

api-reference/audio-isolation-stream.mdx
api-reference/audio-isolation.mdx
mint.json

Reverts elevenlabs/elevenlabs-docs#306

Revert "Add Audio Isolation API docs" until the API is launched

---

api-reference/audio-isolation-stream.mdx
api-reference/audio-isolation.mdx
mint.json

Add Audio Isolation API docs

---

audio-native/overview.mdx
dubbing/overview.mdx
dubbing/studio.mdx
introduction.mdx
troubleshooting/overview.mdx
voiceover-studio/overview.mdx
voices/default-voices.mdx
voices/overview.mdx
voices/voice-lab/overview.mdx
voices/voice-library/overview.mdx
voices/voice-library/payouts.mdx
voices/voice-library/sharing.mdx

Ensuring consistency of quotation marks, correcting a few typos and other issues

Decs refresh corrections

---

speech-synthesis/voice-selection.mdx

- Both links were redirecting to 404

fix: correct links (voice-selection page)

---

conversational-ai-sdks/widget.css
conversational-ai-sdks/widget.js

Update convai widget style

---

api-reference/how-to-use-text-to-sound-effects.mdx
api-reference/reducing-latency.mdx
api-reference/text-to-speech.mdx
audio-native/audio-native-react.mdx
conversational-ai/overview.mdx
speech-synthesis/voice-selection.mdx
voices/default-voices.mdx
voices/overview.mdx

```
mintlify broken-links
-> No broken links found.
```
Note: Our entire documentation site is hosted under the /docs path. Will need to see that all links checked using mintlify dev and the link check command reflect this base path correctly.

fix: all broken links

---

mint.json
release-notes/product-updates.mdx

Before: https://elevenlabs.io/docs/release-notes/release-notes
After: https://elevenlabs-docs-feat-update-changelog.mintlify.app/release-notes/product-updates

feat: use new mintlify <Update> component for Changelog

---

mint.json

feat: add thumbs rating

---

conversational-ai/customization/tools.mdx

The old video I recorded on Tools had an echo on the agent's speech so I re-recorded

New Tools Video with no echo

---

conversational-ai/docs/introduction.mdx

"Shopping assistan ts" -> "Shopping assistants" in the elevenlabs Conversational AI docs, visible in both base md file and the built [site](https://elevenlabs.io/docs/conversational-ai/docs/introduction).

spelling correction

---

conversational-ai/libraries/conversational-ai-sdk-js.mdx

Fix typo on conversational-ai-sdk-js.mdx

---

api-reference/overview.mdx

- Adds the ElevenLabs Postman API url.

feat: add to postman

---

api-reference/get-voices.mdx
api-reference/query-library.mdx
conversational-ai/docs/introduction.mdx
product/audio-native/overview.mdx
product/dubbing/overview.mdx
product/guides/getting-started.mdx
product/introduction.mdx
product/projects/overview.mdx
product/sound-effects/overview.mdx
product/speech-synthesis/overview.mdx
product/troubleshooting/overview.mdx
product/voiceover-studio/overview.mdx
product/voices/voice-lab/overview.mdx
product/voices/voice-library/overview.mdx
product/workspace/overview.mdx

We might need to change the title, b[ut Google docs say they also listen to og:title](https://developers.google.com/search/docs/appearance/title-link) so that might be enough.

[Meta Title] improve duplicate meta titles

---

api-reference/sound-generation.mdx
developer-guides/how-to-use-text-to-sound-effects.mdx

- change characters to credits
- change cost per second from 25 to 20 credits

fix: update sfx cost

---

conversational-ai/docs/agent-setup.mdx
mint.json

Needs to wait for the feature to be released

[ConvAI] Hide publishing guide

---

conversational-ai/customization/client-tools.mdx
conversational-ai/libraries/conversational-ai-sdk-swift.mdx

feat: add client tools swift docs

---

conversational-ai/api-reference/websocket.mdx

adding ws message format for overriding conversation config

adding client overrides for conversation

---

conversational-ai/guides/conversational-ai-twilio.mdx

https://github.com/elevenlabs/elevenlabs-examples/tree/main/examples/conversational-ai/twilio/python-sdk

Twilio Python SDK Update

---

conversational-ai/customization/tools.mdx

Fix cal.com tools reference from startTime to start

Fix cal.com tools reference from startTime to start

---

fern/docs/pages/product-guides/products/projects.mdx
fern/docs/pages/resources/troubleshooting.mdx

Shifted change to new docs as well
Todo: fix images later once have finished other PR for Luke

feat: update regeneration description

---

fern/apis/api/openapi-overrides.yml
fern/apis/api/openapi.json
fern/docs.yml

Also updates openapi.json - for some reasone the order of x-fern attributes changed any ideas why?

Add update-project-content and callback_url

---

fern/conversational-ai/guides/conversational-ai-ghost.mdx
fern/conversational-ai/guides/conversational-ai-squarespace.mdx
fern/conversational-ai/guides/conversational-ai-webflow.mdx
fern/conversational-ai/guides/conversational-ai-wix.mdx
fern/conversational-ai/guides/conversational-ai-wordpress.mdx
fern/docs.yml

No code integration docs for 
-webflow
-wix
-wordpress
-ghost 
-squarespace
If you agree with the content i'll add some images to make it prettier for docs 2.0

feat: add no code walkthroughs

---

fern/docs.yml

chore: fix order.

---

fern/docs/pages/product-guides/administration/billing.mdx

* tighten up content
* add links
* add top level link cards

chore: billing content.

---

fern/conversational-ai/guides/conversational-ai-guide-framer.mdx

move to framer component controlled by elevenlabs account

fix: framer link

---

fern/apis/api/openapi-overrides.yml

from https://eleven-labs-workspace.slack.com/archives/C089SGUJW4R/p1737644755923949

fix: improve PLS endpoint description in overrides

---

fern/api-reference/pages/streaming.mdx
fern/api-reference/pages/websocket.mdx
fern/apis/api/openapi-overrides.yml
fern/docs.yml

Normalized all cases and renamed some endpoints for clarity.

Polish API ref

---

fern/docs/pages/quickstart.mdx

Smal quality of life improvements
* Make it easier to copy the scripts to run
* Add the note at the bottom again because I missed it above and was confused when `play` didn't work.

chore: small qol nits.

---

fern/apis/api/openapi-overrides.yml
fern/docs.yml

Alphabetized items in "Administration section". Also fixed that wayward "Update project" appearing at the bottom of the API reference.

Reorganize API ref

---

fern/apis/convai/asyncapi.yml

https://eleven-labs-workspace.slack.com/archives/D088N43RM6G/p1738064493781179

fix: ws docs

---

fern/apis/api/openapi-overrides.yml

add override explaining current issue with API

fix docs: search param makes source no longer optional

---

fern/docs/pages/changelog/2025-01-27.md

the neverending quest for the perfect changelog

nit: add bulletpoint for docs changelog

---

fern/assets/scripts/widget.js
fern/docs/pages/product-guides/products/studio.mdx

Fixes https://github.com/elevenlabs/elevenlabs-docs/issues/398

Add tooling for .pls files

---

fern/apis/api/openapi-overrides.yml
fern/apis/api/openapi.json

urgent request from seb for enterprise customer

feat: workspace routes

---

fern/conversational-ai/pages/overview.mdx

new pricing is not currently released

feat: new convai pricing

---

fern/conversational-ai/pages/overview.mdx

feat pricing credits toggle

---

fern/conversational-ai/pages/overview.mdx

Updated conv ai included minutes

---

fern/conversational-ai/pages/overview.mdx

-adds supported formats
-bumps up pricing notice

fix: bump up pricing notice and enumerate supported formats

---

fern/conversational-ai/pages/customization/knowledge-base.mdx

noticed we're getting quite a few feedbacks around kb item from url (specifically whether it can scrape the whole site or can update). these are coming in v2 of kb, putting up update for now

add kb from url notice

---

fern/docs/pages/capabilities/text-to-speech.mdx

https://elevenlabs-preview-a4d099fa-6ade-40d4-b198-7fff47791eaf.docs.buildwithfern.com/docs/capabilities/text-to-speech#what-qualifies-as-a-free-regeneration

fix: clarify free regens

---

fern/conversational-ai/pages/guides/twilio-custom-server.mdx

feat: add twilio custom server disclaimer

---

fern/conversational-ai/pages/customization/tools/end-call.mdx

better end call docs

---

fern/docs/pages/best-practices/prompting.mdx
fern/docs/pages/product-guides/products/studio.mdx

- change info on multiple break tags to a note
- add info on alias tags to Prompting page
- add info on pronunciation dictionaries to Prompting page
- add links to sites on generating pronunciation dictionaries to new PD section on Prompting page
- remove links to sites on generating pronunciation dictionaries from Studio page
- add link to new pronunciation dictionaries section of Prompting page to Studio page

Update prompting page

---

fern/apis/api/openapi-overrides.yml
fern/docs/pages/cookbooks/legacy/text-to-speech/streaming.mdx

Adds speed control to the cookbook tutorial.

Update docs to include speed control

---

fern/docs/pages/cookbooks/legacy/dubbing/basics.mdx

we should probably set up some e2e tests so that a changes on xi causes docs tests to fail

fix: remove mode flag

---

fern/conversational-ai/pages/customization/tools/end-call.mdx

fixes empty example end call prompt

feat: add end call prompt example

---

fern/conversational-ai/pages/guides/twilio-dashboard.mdx
fern/docs.yml

fix: update title

---

fern/conversational-ai/pages/customization/audio-saving.mdx
fern/conversational-ai/pages/customization/dynamic-variables/twilio-inbound-integration.mdx
fern/docs.yml

fix: capitalisation

---

fern/conversational-ai/pages/customization/client-events.mdx
fern/docs.yml

docs at /docs/conversational-ai/customization/tools-events/client-events#tool-events

feat: document convai client tools

---

fern/conversational-ai/pages/guides/twilio-outbound-calling.mdx

with thanks to @colbygarland 
recreates #826 without formatting issues

fix: add comma and formatting

---

fern/docs.yml
fern/docs/pages/cookbooks/text-to-speech/supabase-streaming.mdx

Cookbook for the supabase streaming example: https://github.com/elevenlabs/elevenlabs-examples/pull/142

feat: add suapabse tts streaming cookbook.

---

fern/docs.yml
fern/snippets/webhook-hmac-authentication.mdx

- Add next.js webhook event verification example.
- Improve webhook verification example structure.
- Move webhook doc to top level menu.

feat: add next.js webhook example and some small improvements.

---

.cursorrules
fern/docs/pages/changelog/2025-03-10.md

- adds new changelog
- adds new cursorrule to make it easier

Changelog 03-10

---

fern/apis/api/openapi-overrides.yml

Removes overrides since they've been moved upstream..

Remove history overrides

---

fern/docs/pages/models.mdx

Adds an accordion to list limitations of the Flash v2.5 model.

Add considerations to flash v2.5 model page

---

fern/api-reference/pages/websockets.mdx

update code example for input streaming using python sdk

Updated websockets.mdx

---

fern/apis/api/openapi.json
fern/docs/pages/product-guides/administration/workspaces/sharing.mdx

Pull up to date spec with workspace sharing endpoints

Add sharing endpoints

---

fern/conversational-ai/pages/customization/dynamic-variables.mdx

system dynamic variable docs

---

fern/docs.yml
fern/docs/pages/best-practices/prompting/controls.mdx
fern/docs/pages/best-practices/prompting/normalization.mdx
fern/docs/pages/models.mdx

Guide for normalizing text for TTS.

Normalization docs

---

.prettierignore
fern/conversational-ai/pages/customization/personalization.mdx
fern/docs.yml

jozef would like a page with high level overview of personalization options

wip: add personalization page

---

fern/docs.yml

- add language detection also under `Language` section in the nav.

chore: language detection nav.

---

fern/conversational-ai/pages/guides/twilio-outbound-calling.mdx

The project is using Twilio so i just added it on the install dependencies step

fix: add missing dependency

---

fern/conversational-ai/pages/best-practices/voice-design.mdx
fern/docs.yml

makes it clearer this is about designing conversational voices, not how to use voice design
we had some feedback around this in the discord

make clear convai voice design is not a guide

---

fern/docs/pages/models.mdx

@PaulAsjes going to merge this in as our docs are quite out of date on this front but could you lmk on Monday what you think about messaging the concurrency limit (is not a hard limit)

fix concurrency

---

fern/conversational-ai/pages/customization/events.mdx
fern/conversational-ai/pages/customization/tools/agent-transfer.mdx
fern/conversational-ai/pages/customization/tools/overview.mdx
fern/conversational-ai/pages/customization/tools/system-tools.mdx
fern/conversational-ai/pages/workflows/agent-agent-transfer.mdx
fern/docs.yml

want top level docs pages to help ppl figure out where to go

Angelo/summarise tools+events

---

fern/conversational-ai/pages/customization/rag.mdx

add kb limit info

---

.github/scripts/check_links.py
fern/docs.yml
fern/docs/pages/capabilities/dubbing.mdx
fern/docs/pages/capabilities/forced-alignment.mdx
fern/docs/pages/capabilities/sound-effects.mdx
fern/docs/pages/capabilities/speech-to-text.mdx
fern/docs/pages/capabilities/voice-changer.mdx
fern/docs/pages/capabilities/voice-isolator.mdx
fern/docs/pages/capabilities/voices.mdx
fern/docs/pages/developer-guides/cookbooks/dubbing/quickstart.mdx
fern/docs/pages/developer-guides/cookbooks/forced-alignment/quickstart.mdx
fern/docs/pages/developer-guides/cookbooks/sound-effects/quickstart.mdx
fern/docs/pages/developer-guides/cookbooks/speech-to-text/quickstart.mdx
fern/docs/pages/developer-guides/cookbooks/speech-to-text/streaming.mdx
fern/docs/pages/developer-guides/cookbooks/voice-changer/quickstart.mdx
fern/docs/pages/developer-guides/cookbooks/voice-isolator/quickstart.mdx
fern/docs/pages/developer-guides/cookbooks/voices/clone-voice.mdx
fern/docs/pages/developer-guides/cookbooks/voices/voice-design.mdx
fern/docs/pages/quickstart.mdx
fern/snippets/quickstart-api-key.mdx
fern/snippets/quickstart-developer-guides.mdx
fern/snippets/quickstart-install-sdk.mdx

Reverts elevenlabs/elevenlabs-docs#998
Attempt 2, this time with fixed links.

Revamp quickstart page

---

fern/conversational-ai/pages/guides/cascade.mdx
fern/docs.yml

/docs/conversational-ai/guides/llm-cascading

feat: add llm cascade

---

fern/docs/pages/models.mdx

Adding to docs following repeated customer questions on the topic

Adding concurrency limits best practises

---

fern/docs/pages/models.mdx

Incorrect language and guidance used

Reverting concurrency limit reference

---

fern/conversational-ai/pages/customization/knowledge-base.mdx

fix kb docs info

---

fern/docs/pages/product-guides/administration/workspaces/overview.mdx
fern/docs/pages/product-guides/administration/workspaces/sharing.mdx

Updating public docs for https://github.com/elevenlabs/xi/pull/9786

Workspace API keys become service accounts

---

fern/conversational-ai/pages/customization/tools/agent-transfer.mdx
fern/conversational-ai/pages/customization/tools/end-call.mdx
fern/conversational-ai/pages/customization/tools/human-transfer.mdx
fern/conversational-ai/pages/customization/tools/language-detection.mdx
fern/conversational-ai/pages/customization/tools/system-tools.mdx

This reverts commit 596d9adce573b66fd6a2e799011fbd7a5d2cce35.

Revert "fix: revert breaking change"

---

fern/conversational-ai/pages/customization/tools/agent-transfer.mdx
fern/conversational-ai/pages/customization/tools/end-call.mdx
fern/conversational-ai/pages/customization/tools/human-transfer.mdx
fern/conversational-ai/pages/customization/tools/language-detection.mdx
fern/conversational-ai/pages/customization/tools/system-tools.mdx
fern/docs/pages/changelog/2025-05-05.md

updates import and updates changelog

[docs] fix breaking change

---

fern/docs/pages/product-guides/administration/workspaces/sso.mdx

Improving Okta SAML setup instructions

---

fern/conversational-ai/pages/guides/telephony/plivo.mdx
fern/conversational-ai/pages/guides/telephony/telnyx.mdx
fern/conversational-ai/pages/guides/twilio-custom-server.mdx
fern/conversational-ai/pages/guides/twilio-outbound-calling.mdx
fern/docs.yml

-extract phone number section
-move cascading guide to new llm section
-add transfers section

refactor convai docs 

---

.github/scripts/check_links.py
fern/docs.yml
fern/docs/pages/best-practices/conversational-agents.mdx

for new multi context wss /docs/best-practices/conversational-agents

[convai] agent best practice

---

fern/apis/api/asyncapi.yml

fix asyncapi

---

fern/conversational-ai/pages/customization/llm/optimising-cost.mdx
fern/conversational-ai/pages/overview.mdx

in /docs/conversational-ai/overview

[convai] add silence pricing disclaimer

---

fern/docs/pages/developer-guides/cookbooks/text-to-speech/request-stitching.mdx

With the new v2 of the SDKs, request stitching is a lot easier.

Update request stitching guide

---

fern/conversational-ai/pages/customization/dynamic-variables.mdx

/docs/conversational-ai/customization/personalization/dynamic-variables

add secret dyn vars docs

---

fern/conversational-ai/pages/legal/gdpr.mdx

fix gdpr docs

---

fern/conversational-ai/pages/guides/sip-trunking.mdx

/docs/conversational-ai/phone-numbers/sip-trunking

add audio codec

---

fern/conversational-ai/pages/customization/custom-llm/overview.mdx

/docs/conversational-ai/customization/llm/custom-llm

[convai] custom llm buffer words

---

fern/docs/pages/product-guides/administration/workspaces/sso.mdx

Add help text for common OIDC errors

OIDC common errors

---

fern/conversational-ai/pages/guides/burst-pricing.mdx
fern/docs.yml

/docs/conversational-ai/guides/burst-pricing

[convai] burst pricing

---

fern/conversational-ai/pages/legal/disclosure.mdx
fern/docs.yml

force merging as request from legal

disclosure

---

fern/docs.yml

See https://eleven-labs-workspace.slack.com/archives/C088W65MRPW/p1750184019891839

Add backlinks

---

.pre-commit-config.yaml

quick pr to add pre commit that runs pnpm fmt

pnpm fmt precommit 

---

fern/conversational-ai/pages/guides/sip-trunking.mdx

Nit fix on the codecs supported for SIP trunking

SIP codecs
