elevenlabs/elevenlabs-docs

api-reference/integration-guides/react-text-to-speech-guide.mdx

The PR contains changes in the [Leveraging ElevenLabs’ AudioStream React Component](https://elevenlabs.io/docs/api-reference/integration-guides/react-text-to-speech-guide#leveraging-elevenlabs-audiostream-react-component) section of the docs.
- #79 
- #74 
- Updated the above mentioned section with how a user can create the `AudioStream` component and how they can use it in their app
- Added a note section explaining that `AudioStream` and `SpeechStreamComponent` components are essentially the same.
- Added a new info on how an user can extend the component
- Added syntax highlighting for the existing code blocks.

fix: DOCS - React Guide: Updated notes section

---

mint.json

I've used the wrong one.
This is actually the production one.

Change Google Analytics Measurement ID

---

audio-native/overview.mdx

In our audio native docs, we say that we are linking to our blog as an example but we actually link to our speech synthesis page

Fix broken link to blog example on audionative

---

api-reference/getting-started.mdx

Current Docs show the URLS not hyperlinked.
Small Fix to change. CC @lharries

Chore: Fix URLs on Getting Started

---

speech-synthesis/models.mdx

removed mention of turbo v2.5 being 25% faster

Update models to reflect true latency

---

speech-synthesis/voice-selection.mdx

Add `/docs` to start of the path for the four links on the [Voice Selection page](https://elevenlabs.io/docs/speech-synthesis/voice-selection). Each of these links currently leads to a 404 without that in the link.

Fix broken links in voice-selection.mdx

---

api-reference/websockets.mdx

The sample response message JSON was missing a comma after the `charDurationsMs` fields for the two alignment objects in the response message.

Fix invalid JSON in websockets.mdx

---

api-reference/websockets.mdx

Pls fix the broken link to OpenAI example in websockets.mdx, consider that the link does not work on GitHub previews because of '-' in the title, but it works on the website.

Fix broken link to OpenAI example in websockets.mdx

---

api-reference/specifying-server-location.mdx
mint.json

The typescript API depends on
https://github.com/elevenlabs/elevenlabs-js/pull/93 to be merged & released since currently the environment is ignored.

Add guide for specifying server location

---

api-reference/integrating-with-twilio.mdx

The `textToSpeech.convert` method in the latest version of the `elevenlabs-js` SDK now returns a different type of stream.
- Updated the guide to convert the response from `textToSpeech.convert` into a Node.js readable stream using `Readable.from(response)`.
- This ensures the Twilio guide is compatible with the latest elevenlabs-js SDK.
Reference Issue: [elevenlabs-js/issues/90](https://github.com/elevenlabs/elevenlabs-js/issues/90)

fix: twilio guide compatibility with updated elevenlabs-js SDK

---

api-reference/generate-voice-parameters.mdx
api-reference/generate-voice.mdx
api-reference/ttv-create-previews.mdx
api-reference/ttv-create-voice-from-preview.mdx
mint.json
openapi.json

We should update the docs in backend & clean up the examples a bit too as a follow up.

Add TTV docs, mark the old voice generation as deprecated

---

openapi.json

The openapi.json file is manually edited right now, need to patch this in as regenerating from upstream would cause a lot of diffs. Need to fix that later.

Patch in openapi changes for quality_check_on

---

conversational-ai/libraries/conversational-ai-sdk-js.mdx
mint.json

Some users don't notice "javascript sdks" is expandable and there is also React SDK. I don't see an option to force it to be expanded in mintlify (will ask), in the meantime we can flatten the structure.
I've put react above js, and renamed "client" to "javascript" to keep it clearer.

Unnest the convai SDKs

---

fern/conversational-ai/customization/conversation-configuration.mdx

camel case is the correct usage of firstMessage when overriding the agent

Dynamic Conversation - Updating first_message to firstMessage

---

fern/docs.yml

This removes the `nothing` audience so that all the endpoints render appropriately in the API Reference

chore: remove nothing audience

---

fern/assets/styles.css
fern/assets/widget.js

Updates the widget styles to match the new docs:
Adds new terms and conditions as described by [this docs](https://docs.google.com/document/d/1qm83rF9GP3gbOmJcKQbna0cDaCYXicaQJpWhW-le4lA/edit?pli=1&tab=t.0)

[ConvAI] Add terms and fix widget styles

---

fern/product/troubleshooting/regenerations.mdx

Simple PR to reflect that auto regeneration is now only automatically applied for bulk conversion and cant be enabled otherwise.
Before: 
After:

fix: update docs to reflect auto-regeneration automatically applied

---

fern/apis/api/openapi-overrides.yml
fern/docs/pages/product-guides/voices/voice-design.mdx
fern/docs/pages/quickstart.mdx

* Align API ref naming to product guide naming
* Add useful links to product guide
* Align quickstart naming with product naming
Todo:
[ ] Figure out how to rename `ENDPOINTS > Text to Voice` to `ENDPOINTS > Voice design`
[ ] Prevent fern from sorting endpoints alphabetically

Docs 2.0: Voice design docs nits

---

fern/docs/pages/quickstart.mdx

This makes a few changes to the quickstart:
* Prefer `.env` over exporting keys to bash config file
* Tabbed interface for installing an SDK
* Removed `node-fetch` from JS example code
* A bit of wordsmithing

Streamline quickstart

---

fern/conversational-ai/pages/libraries/react.mdx

The method is called startSession, not startConversation

Fix typo in react convAI description page

---

fern/docs/pages/capabilities/speech-to-text.mdx
fern/docs/pages/cookbooks/speech-to-text/synchronous.mdx

Link directly to the cookbook instead of the quickstart.

Link to developer tutorial instead of quickstart

---

fern/docs/pages/capabilities/sound-effects.mdx

Fix a missing character in the url

Fix 90s drum loop mp3 url

---

fern/conversational-ai/pages/customization/overrides.mdx

Fixing a broken link to the dynamic variables page

Fix: broken link to dynamic variable page

---

fern/docs.yml
fern/docs/pages/product-guides/audio-tools/audio-native/framer.mdx
fern/docs/pages/product-guides/audio-tools/audio-native/ghost.mdx
fern/docs/pages/product-guides/audio-tools/audio-native/squarespace.mdx
fern/docs/pages/product-guides/audio-tools/audio-native/webflow.mdx
fern/docs/pages/product-guides/audio-tools/audio-native/wix.mdx
fern/docs/pages/product-guides/audio-tools/audio-native/wordpress.mdx

adds a code snippet for users to copy and paste in the docs, with the seo link james wanted.
unfortunately we can't retroactively change links used so this will have to suffice
e.g: adds this to 
/docs/product-guides/audio-tools/audio-native/squarespace

fix: add SEO optimised code snippet

---

fern/assets/scripts/widget.js

Under some circumstances, the agent performing a redirect causes the init script to execute again, duplicating the widget on our website
Also removes the hardcoded terms since those are now configured via the agent config.

Fix duplicated ConvAI widget

---

fern/apis/api/generators.yml
fern/apis/api/openapi-overrides.yml
fern/docs.yml

This PR: 
- Removes the legacy `projects` endpoints from the docs
- Adds anchors for ConvAI endpoints so they stay in sync
- Removes unused redirects

Docs clean up

---

fern/conversational-ai/pages/customization/dynamic-variables/twilio-inbound-integration.mdx

I believe type field should be part of the example json as the API docs requires it: https://elevenlabs.io/docs/conversational-ai/api-reference/conversational-ai/websocket#send.Conversation%20Initiation%20Client%20Data
Twilio call fails without visible errors if users set up Client Initiation Webhook without this attribute. Personally spent hours trying to debug it after following the tutorial. Either this or a better error handling for the Client Initiation Webhook is needed.

Add required type field to example at twilio-inbound-integration.mdx

---

fern/conversational-ai/pages/customization/dynamic-variables.mdx

Typo error on the name of the dynamic variable (Conversation AI), `system__call_id` should be `system__call_sid`.
<br/>
Screenshot from the docs:
Screenshot from the playground:

Fix typo in dynamic variables documentation

---

fern/conversational-ai/pages/customization/overrides.mdx
fern/conversational-ai/pages/customization/widget.mdx

Updates the override examples for the convai widget.
The `override-config` is an attribute (with a confusing name) used for dev purposes to override the entire config of the widget, not the agent overrides.
https://github.com/elevenlabs/xi/pull/9386 introduces a proper way to configure those overrides ~~so lets wait till that goes live and update the docs~~ it's live now so we can update the docs

Fix convai widget override examples

---

fern/apis/api/openapi-overrides.yml
fern/docs.yml

Fixes broken link `https://elevenlabs.io/docs/api-reference/voices/get-all` on docs

docs: Update get-all voices links

---

fern/conversational-ai/pages/guides/batch-calls.mdx

Added concurrency information for batch calls - they use up to 70% of plan limits.

Add batch calls concurrency info

---

fern/apis/api/openapi.json

- Capitalize tag names that were being used for the display name of some docs sections
Before:
After:

fix: capitalize tags for errant section names

---

fern/conversational-ai/pages/libraries/react.mdx

Adds docs around new WebRTC mode. The Next.js guide is intentionally kept using websockets as the default. This will probably change as we gain confidence in WebRTC.

Update ConvAI react docs

---

examples/snippets/python/quickstart_tts.py
fern/snippets/generated/quickstart_tts.mdx

Hi, 
I was playing around with your API quickstart in your docs and found a missing import in the python example snippet. 
I added the import to `quickstart_tts.py` and then ran `pnpm run snippets:generate` which generated the `quickstart_tts.mdx`.
While fixing this also noticed that there was a differente approach to initialising the client. 
```python
client = ElevenLabs()
```
versus
```python
elevenlabs = ElevenLabs(
api_key=os.getenv("ELEVENLABS_API_KEY"),
)
```
I went with the latter since the first one didn't work locally.
Feel free to let me know if there are any mistakes. Looking forward to your comments 🙌
Cheers!

added import os to the quickstart guide

---

fern/docs.yml

Reasoning:
- Better performance during tool calls, Claude 3.5 consistently hallucinates when responding to the messages `pause` and `skip turn`, but Claude 4 does not do this.

feat: upgrade to using claude 4 over claude 3.5

---

fern/apis/api/asyncapi.yml
fern/apis/api/openapi-overrides.yml
fern/apis/convai/asyncapi.yml
fern/apis/convai/openapi.json

Switching the base url to a different region isn't working right now. Neither SDK nor FE:
https://elevenlabs.io/docs/api-reference/text-to-speech/v-1-text-to-speech-voice-id-stream-input
https://elevenlabs.io/docs/conversational-ai/api-reference/conversational-ai/websocket
https://github.com/elevenlabs/elevenlabs-python/blob/main/src/elevenlabs/environment.py
This seem to fix the FE pages in the preview. Hopefully the SDK too.

Fix websockets URLs for each region

---

fern/docs/pages/developer-guides/cookbooks/text-to-speech/streaming.mdx

Requests were not authorized if the code was copied

No load_dotenv() in text-to-speech/streaming examples
